[versions]
assertj = "3.27.6"
equalsVerifier = "4.3"
jackson = "2.20.1"
java-parser = "3.28.0"
jcommander = "1.82"
jetbrains-annotations = "26.0.2-1"
junit = "6.0.2"
logback = "1.5.24"

[libraries]
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
equalsVerifier = { module = "nl.jqno.equalsverifier:equalsverifier", version.ref = "equalsVerifier" }
jackson-dataformat-xml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-xml", version.ref = "jackson" }
java-parser = { module = "com.github.javaparser:javaparser-core", version.ref = "java-parser" }
jcommander = { module = "com.beust:jcommander", version.ref = "jcommander" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

[plugins]
gradle-git-properties = { id = "com.gorylenko.gradle-git-properties", version = "2.5.4" }
shadow = { id = "com.gradleup.shadow", version = "9.3.1" }
